apiVersion: v1
kind: ConfigMap
metadata:
  name: myid-configmap
data:
  myid-config-setup.sh: |
    #!/bin/sh
    ZK_SERVER_ID=$((${HOSTNAME##*-}+1))
    echo "${ZK_SERVER_ID}" > "$ZK_DATA_DIR/myid"
---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zk
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: Always
          image: "leonardorocha1990/pi-zookeeper:1.0.0-SNAPSHOT"
          env:
            - name: ZK_DATA_DIR
              value: /opt/zookeeper/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          command:
            - sh
            - -c
            - "cp /tmp/zookeeper/* /opt/zookeeper ; ls -la /opt/zookeeper ; chmod 777 /opt/zookeeper/myid-config-setup.sh;chmod +x /opt/zookeeper/myid-config-setup.sh ; /opt/zookeeper/myid-config-setup.sh ; zkServer.sh start-foreground /opt/zookeeper/conf/zoo.cfg"
          volumeMounts:
            - name: datadir
              mountPath: /opt/zookeeper/data
            - name: myid-config
              mountPath: /tmp/zookeeper
      volumes:
        - name: myid-config
          configMap:
            name: myid-configmap
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi